DROP TABLE playerDetails;
CREATE TABLE playerDetails (
    JERSY_NUMBER number(3),
    NAME varchar(15),
    POSITION number(2),
    AVERAGE number(4,2),
    CENTURY number(3),
    HALF_CENTURY number(3),
    AGE number(2)
);
--DESCRIBE playerDetails;
INSERT INTO playerDetails (JERSY_NUMBER, NAME, POSITION, AVERAGE, CENTURY, HALF_CENTURY, AGE) VALUES (28, 'Tamim', 1, 40.25, 9, 29, 35);
INSERT INTO playerDetails (JERSY_NUMBER, NAME, POSITION, AVERAGE, CENTURY, HALF_CENTURY, AGE) VALUES (66, 'Anamul', 2, 35.75, 3, 13, 25);
INSERT INTO playerDetails (JERSY_NUMBER, NAME, POSITION, AVERAGE, CENTURY, HALF_CENTURY, AGE) VALUES (75, 'Shakib', 3, 39.75, 7, 27, 35);
INSERT INTO playerDetails (JERSY_NUMBER, NAME, POSITION, AVERAGE, CENTURY, HALF_CENTURY, AGE) VALUES (15, 'Mushfiq', 4, 37.15, 5, 19, 35);
INSERT INTO playerDetails (JERSY_NUMBER, NAME, POSITION, AVERAGE, CENTURY, HALF_CENTURY, AGE) VALUES (30, 'Mahmudullah', 5, 33.30, 4, 17, 37);
SELECT * FROM playerDetails;